esphome:
  name: "saunacontroller"
  friendly_name: "saunacontroller"
  on_boot:
    priority: -100
    then:
      - climate.control:
          id: sauna_thermostat
          mode: "OFF"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Example configuration entry
debug:
  update_interval: 5s

# Logger must be at least debug (default)
logger:
  level: debug

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret saunacontroller_ap_ssid
    password: !secret saunacontroller_ap_password

web_server:
  port: 80
  version: 3
  auth:
    username: !secret saunacontroller_webserver_user
    password: !secret saunacontroller_webserver_password
  sorting_groups:
    - id: group_sauna
      name: "Sauna"
      sorting_weight: 10
    - id: group_verdampfer
      name: "Verdampfer"
      sorting_weight: 20
    - id: group_infrarot
      name: "Infrarot"
      sorting_weight: 30
    - id: group_beleuchtung
      name: "Beleuchtung"
      sorting_weight: 40
    - id: group_system
      name: "System"
      sorting_weight: 50

captive_portal:

switch:
  - platform: gpio
    id: saunaofen
    pin: GPIO16
    restore_mode: ALWAYS_OFF
    internal: true
  - platform: gpio
    id: saunaverdampfer
    pin: GPIO17
    restore_mode: ALWAYS_OFF
    internal: true
  - platform: restart
    name: "ESP Restart"
    web_server:
      sorting_group_id: group_system
      sorting_weight: 10
  - platform: template
    id: hygrostat_switch
    name: "Hygrostat"
    icon: "mdi:water-percent"
    restore_mode: ALWAYS_OFF
    web_server:
      sorting_group_id: group_verdampfer
      sorting_weight: 10
    lambda: |-
      return id(hygrostat_active);
    turn_on_action:
      - globals.set:
          id: hygrostat_active
          value: 'true'
    turn_off_action:
      - globals.set:
          id: hygrostat_active
          value: 'false'
      - switch.turn_off: saunaverdampfer

one_wire:
  - pin: GPIO23
    platform: gpio
    #update_interval: 30s
    id: "temperature_hub"

# Temperatur / Luftfeuchtesensor müssen angeschlossen sein, sonst kein Booten möglich: Recovery failed, SCL is held low on the bus
i2c:
  - id: i2c_bus_a
    sda: GPIO33
    scl: GPIO32
    scan: False

sensor:
  - platform: dallas_temp
    address: 0x4a3c01b607ccd828
    name: "Temperatur Steuergerät"
    web_server:
      sorting_group_id: group_system
      sorting_weight: 20
  - platform: am2320
    i2c_id: i2c_bus_a
    setup_priority: -1000
    address: 0x5C
    temperature:
      id: temperatur_sauna
      name: "Temperatur Sauna"
      accuracy_decimals: 1
      web_server:
        sorting_group_id: group_sauna
        sorting_weight: 20
    humidity:
      id: luftfeuchte_sauna
      name: "Luftfeuchte Sauna"
      accuracy_decimals: 1
      web_server:
        sorting_group_id: group_verdampfer
        sorting_weight: 30
    update_interval: 30s
  - platform: uptime
    type: seconds
    name: "Uptime Sensor"
    web_server:
      sorting_group_id: group_system
      sorting_weight: 30
  - platform: debug
    free:
      name: "Heap Free"
      web_server:
        sorting_group_id: group_system
        sorting_weight: 40
    block:
      name: "Heap Max Block"
      web_server:
        sorting_group_id: group_system
        sorting_weight: 50
    loop_time:
      name: "Loop Time"
      web_server:
        sorting_group_id: group_system
        sorting_weight: 60

#LED Stripes - GPI02 & GPIO15
light:
  - platform: monochromatic
    output: gpio_18
    name: "Infrarotstrahler 1"
    web_server:
      sorting_group_id: group_infrarot
      sorting_weight: 10
  - platform: monochromatic
    output: gpio_19
    name: "Infrarotstrahler 2"
    web_server:
      sorting_group_id: group_infrarot
      sorting_weight: 20
  - platform: esp32_rmt_led_strip
    rgb_order: BGR
    pin: GPIO2
    num_leds: 16
    #rmt_channel: 0
    chipset: ws2812
    name: "LED Salzkristall-Leuchten"
    web_server:
      sorting_group_id: group_beleuchtung
      sorting_weight: 10
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO15
    num_leds: 213
    #rmt_channel: 1
    chipset: ws2812
    name: "LED Streifen"
    web_server:
      sorting_group_id: group_beleuchtung
      sorting_weight: 20
  #   effects:
  #     - pulse:
  #         name: "Fast Pulse"
  #         transition_length: 0.5s
  #         update_interval: 0.5s
  #         min_brightness: 0%
  #         max_brightness: 100%
  #     - random:
  #         name: Random Effect With Custom Values
  #         transition_length: 5s
  #         update_interval: 7s
  #     - strobe:
  #         name: Strobe Effect With Custom Values
  #         colors:
  #           - state: true
  #             brightness: 100%
  #             red: 100%
  #             green: 90%
  #             blue: 0%
  #             duration: 500ms
  #           - state: false
  #             duration: 250ms
  #           - state: true
  #             brightness: 100%
  #             red: 0%
  #             green: 100%
  #             blue: 0%
  #             duration: 500ms
  #     - flicker:
  #         name: Flicker Effect With Custom Values
  #         alpha: 95%
  #         intensity: 1.5%
  #     - addressable_rainbow:
  #         name: Rainbow Effect With Custom Values
  #         speed: 10
  #         width: 50

#Infrarotstrahler - GPIO18 / GPIO19
output:
  - platform: ac_dimmer
    gate_pin: GPIO18
    id: gpio_18
    zero_cross_pin:
      number: GPIO5
      mode:
        input: true
      inverted: yes
      allow_other_uses: true
  - platform: ac_dimmer
    gate_pin: GPIO19
    id: gpio_19
    zero_cross_pin:
      number: GPIO5
      mode:
        input: true
      inverted: yes
      allow_other_uses: true

text_sensor:
  - platform: version
    name: "ESPHome Version"
    web_server:
      sorting_group_id: group_system
      sorting_weight: 70
  - platform: debug
    device:
      name: "Device Info"
      web_server:
        sorting_group_id: group_system
        sorting_weight: 80
    reset_reason:
      name: "Reset Reason"
      web_server:
        sorting_group_id: group_system
        sorting_weight: 90

# Standalone Sauna Controller (ohne Home Assistant)
climate:
  - platform: thermostat
    id: sauna_thermostat
    name: "Sauna Thermostat"
    sensor: temperatur_sauna
    default_preset: Home
    on_boot_restore_from: default_preset
    preset:
      - name: Home
        default_target_temperature_low: 80
    min_heating_off_time: 0s
    min_heating_run_time: 0s
    min_idle_time: 0s
    heat_deadband: 0.3
    heat_overrun: 0.3
    visual:
      min_temperature: 20
      max_temperature: 90
      temperature_step: 1.0
    heat_action:
      - switch.turn_on: saunaofen
    idle_action:
      - switch.turn_off: saunaofen
    startup_delay: true
    web_server:
      sorting_group_id: group_sauna
      sorting_weight: 10

number:
  - platform: template
    id: target_humidity
    name: "Ziel-Luftfeuchtigkeit"
    unit_of_measurement: "%"
    icon: "mdi:water-percent"
    min_value: 30
    max_value: 70
    step: 1
    initial_value: 50
    restore_value: true
    optimistic: true
    web_server:
      sorting_group_id: group_verdampfer
      sorting_weight: 20

  - platform: template
    id: hygrostat_dry_tolerance
    name: "Hygrostat Toleranz (trocken)"
    unit_of_measurement: "%"
    icon: "mdi:arrow-down"
    min_value: 1
    max_value: 10
    step: 1
    initial_value: 3
    restore_value: true
    optimistic: true
    web_server:
      sorting_group_id: group_verdampfer
      sorting_weight: 40

  - platform: template
    id: hygrostat_wet_tolerance
    name: "Hygrostat Toleranz (feucht)"
    unit_of_measurement: "%"
    icon: "mdi:arrow-up"
    min_value: 1
    max_value: 10
    step: 1
    initial_value: 3
    restore_value: true
    optimistic: true
    web_server:
      sorting_group_id: group_verdampfer
      sorting_weight: 50

globals:
  - id: hygrostat_active
    type: bool
    restore_value: false
    initial_value: 'false'

interval:
  - interval: 10s
    then:
      - lambda: |-
          if (!id(hygrostat_active)) {
            return;
          }
          if (!id(luftfeuchte_sauna).has_state()) {
            return;
          }
          float current = id(luftfeuchte_sauna).state;
          float target = id(target_humidity).state;
          float dry_tol = id(hygrostat_dry_tolerance).state;
          float wet_tol = id(hygrostat_wet_tolerance).state;

          if (current < target - dry_tol) {
            id(saunaverdampfer).turn_on();
          } else if (current > target + wet_tol) {
            id(saunaverdampfer).turn_off();
          }
