esphome:
  name: "saunacontroller"
  friendly_name: "saunacontroller"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "saunacontroller"
    password: "WZkaXyGeW2XD"

captive_portal:

switch:
  - name: saunaofen_power
    platform: gpio
    pin: GPIO15
  - name: saunaverdampfer_power
    platform: gpio
    pin: GPIO16

dallas:
  - pin: GPIO23
    update_interval: 30s
    id: "temperature_hub"

sensor:
  - platform: dallas
    address: 0x4a3c01b607ccd828
    name: "Temperatur Sauna Decke"
  - platform: dallas
    address: 0x103c01b607f9b228
    name: "Temperatur Sauna Mitte"
  - platform: dallas
    address: 0x703c01b6076f3a28
    name: "Temperatur Sauna Zwischen Wand und Sauna"
  - platform: dallas
    address: 0xd83c01b607bd7a28
    name: "Temperatur Saunacontroller"

web_server:
  port: 80